### ISSUE TITLE
need update

### ISSUE THREAD

**Issue by y5hu** [sisl/pygments-style-algfordm#2]
hi, could you please update this pygments style to match the newest version of the book?

**Comment by mykelk** [comment]
@tawheeler Is this not what we are using currently?

**Comment by tawheeler** [comment]
According to `diff` on my local copy of `algfordm.py` vs. the github version, they are identical. @theshuyu, are you seeing a difference?

**Comment by y5hu** [comment]
I want to use `algfordm.py` in `minted`.

Here's an example:
``` latex
\documentclass{article}

\usepackage{fontspec}
\setmonofont[Scale=MatchLowercase]{JuliaMono}[
  Extension      = .ttf,
  UprightFont    = *-Regular,
  BoldFont       = *-Bold,
  ItalicFont     = *-RegularItalic,
  BoldItalicFont = *-BoldItalic
]

\usepackage{minted}
\usemintedstyle{algfordm}


\begin{document}

% from book p26
\begin{minted}{julia}
# requires convenience functions from appendix G.5
X = Variable(:x, 2)
Y = Variable(:y, 2)
Z = Variable(:z, 2)
ϕ = Factor([X, Y, Z], FactorTable(
    (x=1, y=1, z=1) => 0.08, (x=1, y=1, z=2) => 0.31,
    (x=1, y=2, z=1) => 0.09, (x=1, y=2, z=2) => 0.37,
    (x=2, y=1, z=1) => 0.01, (x=2, y=1, z=2) => 0.05,
    (x=2, y=2, z=1) => 0.02, (x=2, y=2, z=2) => 0.07,
))
\end{minted}

\end{document}
```

yields:
<img width="698" alt="1" src="https://github.com/sisl/pygments-style-algfordm/assets/117559681/ac3bc7d4-8047-4700-ab18-8d6e8842c925">

(book p26)

<img width="705" alt="2" src="https://github.com/sisl/pygments-style-algfordm/assets/117559681/e2fe9fba-a573-4e8f-93eb-dd5369db6c4e">

**Comment by mykelk** [comment]
Can you confirm which version of pygmentize you are using with `pygmentize -V`?

**Comment by y5hu** [comment]
`Pygments version 2.15.1, (c) 2006-2023 by Georg Brandl, Matthäus Chajdas and contributors.`

**Comment by mykelk** [comment]
Thanks, I'll be looking into this.

**Comment by mykelk** [comment]
I will provide an updated style that is consistent with the Julia lexer that is built into the newest version of Pygments. For the book we were using our own lexer:
https://github.com/sisl/pygments-julia
Minted does not yet support custom lexers, but pythontex (used for the book) does.

**Comment by y5hu** [comment]
Thanks :-)

**Comment by mossr** [comment]
@theshuyu another option is to use the `listings` package with this custom Julia style: https://github.com/mossr/julia-mono-listings

**Comment by mykelk** [comment]
I looked into this a bit more, and it is not possible to support the Julia lexer that is in the current version of Pygments. Sadly, it does not support a number of the key token types that are required by our style. For example, it does not support `Name.Function` and `Name.Variable`. It looks like they were considering support for functions, but lines 82-83 are commented out here:
https://github.com/pygments/pygments/blob/fcd64b60bfbe4a74529394e722c784b3547745a3/pygments/lexers/julia.py

Of course, we would be perfectly happy for someone to pull out whatever functionality they want from our implementation here:
https://github.com/sisl/pygments-julia
and incorporate it into the built-in lexer.

For now though, if you want the book's syntax highlighting, you will need to used pythontex with our custom pygments-julia lexer. (Or wait until minted supports custom lexers.)
